---
# handlers file

- name: reload systemd
  command: systemctl daemon-reload
  become: true

- name: restart consul
  service:
    name: consul
    state: restarted
  become: true

- name: reload consul
  service:
    name: consul
    state: reloaded
  become: true