---
- include: config.yml

- name: Determine if systemd is present in system
  stat:
    path: /etc/systemd
  register: systemd_dir
  changed_when: False

- include: systemd.yml
  when: hashicorp_consul_service_enabled|bool == true and systemd_dir.stat.exists
