---
- name: Copy systemd service files for Consul
  copy:
    src: files/usr/lib/systemd/system/consul.service
    dest: /usr/lib/systemd/system/consul.service
  become: true
  notify:
    - reload systemd
    - restart consul
    
- name: Enable and start Consul service
  service:
    name: consul
    state: started
    enabled: true
  become: true
    