---
- name: Add Consul user
  user:
    name: consul
    createhome: no
    shell: /sbin/nologin
  become: true
    
- name: Copy systemd service files for Consul
  copy:
    src: files/usr/lib/systemd/system/consul.service
    dest: /usr/lib/systemd/system/consul.service
  become: true
  notify:
    - reload systemd
    - restart consul

- name: Generate Consul service default from template
  template:
    src: etc/default/consul.j2
    dest: /etc/default/consul
    owner: consul 
    mode: 0755
  become: true
  notify:
    - restart consul

- name: Ensure {{ hashicorp_consul_config_dir }} directory exists
  file:
    path: "{{ hashicorp_consul_config_dir }}"
    state: directory
    owner: consul 
    mode: 0755
  become: true

- name: Copy Consul configuration files
  copy:
    src: "{{ item }}"
    dest: "{{ hashicorp_consul_config_dir }}/"
  with_items: "{{ hashicorp_consul_config_files }}"
  become: true
  become_user: consul
  notify:
    - reload consul

- name: Generate Consul config file based on key-value configuration
  copy:
    content: "{{ hashicorp_consul_kv_config | to_nice_json }}"
    dest: "{{ hashicorp_consul_config_dir }}/00-generated.json"
  become: true
  notify:
    - reload consul

- name: Ensure {{ hashicorp_consul_data_dir }} directory exists
  file:
    path: "{{ hashicorp_consul_data_dir }}"
    state: directory
    owner: consul 
    mode: 0755
  become: true
  notify:
    - reload consul
    
- name: Enable and start Consul service
  service:
    name: consul
    state: started
    enabled: true
  become: true
    