---
- name: Copy systemd related files for Consul
  copy:
    src: files/usr/lib/systemd/system/consul.service
    dest: /usr/lib/systemd/system/consul.service
  become: true
  notify:
    - reload systemd
    - restart consul

- name: Add Consul user
  user:
    name: consul
    createhome: no
    shell: /sbin/nologin
  become: true
    
- name: Ensure /etc/opt/consul.d directory exists
  file:
    path: "/etc/opt/consul.d"
    state: directory
    owner: consul 
    mode: 0755
  become: true

- name: Copy Consul configuration files
  copy:
    src: "files/etc/opt/consul.d/"
    dest: /etc/opt/consul.d
  become: true
  become_user: consul

- name: "Check if local directory {{ playbook_dir }}/files/etc/opt/consul.d exists" 
  local_action: stat path="{{ playbook_dir }}/files/etc/opt/consul.d"
  register: consul_d_dir
  ignore_errors: True

- name: Copy Consul configuration files under {{ playbook_dir }}/files/etc/opt/consul.d
  copy:
    src: "{{ playbook_dir }}/files/etc/opt/consul.d/"
    dest: /etc/opt/consul.d
  when: consul_d_dir.stat.exists
  become: true
  become_user: consul

- name: Ensure /var/opt/consul directory exists
  file:
    path: "/var/opt/consul"
    state: directory
    owner: consul 
    mode: 0755
  become: true

- name: "Check if local file {{ playbook_dir }}/files/etc/default/consul exists" 
  local_action: stat path="{{ playbook_dir }}/files/etc/default/consul"
  register: default_consul_file
  ignore_errors: True

- name: "Copy file {{ playbook_dir }}/files/etc/default/consul to /etc/default/consul"
  copy: 
    src: "{{ playbook_dir }}/files/etc/default/consul"
    dest: /etc/default/consul
    owner: consul 
    mode: 0755
  when: default_consul_file.stat.exists
  become: true
  notify:
    - restart consul

- name: "Check if local file {{ playbook_dir }}/files/etc/sysconfig/consul exists" 
  local_action: stat path="{{ playbook_dir }}/files/etc/sysconfig/consul"
  register: default_consul_file
  ignore_errors: True

- name: "Copy file {{ playbook_dir }}/files/etc/sysconfig/consul to /etc/sysconfig/consul"
  copy: 
    src: "{{ playbook_dir }}/files/etc/sysconfig/consul"
    dest: /etc/sysconfig/consul
    owner: consul 
    mode: 0755
  when: default_consul_file.stat.exists
  become: true
  notify:
    - restart consul

- name: Enable and start Consul service
  service:
    name: consul
    state: started
    enabled: true
  become: true
    